In [5]:
import tensorflow as tf
#from keras.models import load_model
from keras.preprocessing import image
import numpy as np

# dimensions of our images
img_width, img_height = 128, 128

# load the model we saved
model = tf.keras.models.load_model('./model_80-20 final.h5')
model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [3]:
img = image.load_img('images_08_1.png', target_size=(img_width, img_height))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)

images = np.vstack([x])
classes = model.predict_classes(images, batch_size=10)
print(classes)

if classes == 1:
    prediction = 'Tuberculosis'
else:
    prediction = 'Normal'
print(prediction)

[1]
Tuberculosis


In [7]:
print(image.img_to_array(img))

[[[ 7.  7.  7.]
  [ 8.  8.  8.]
  [ 7.  7.  7.]
  ...
  [ 6.  6.  6.]
  [ 5.  5.  5.]
  [ 4.  4.  4.]]

 [[ 8.  7.  8.]
  [12. 11. 12.]
  [14. 13. 14.]
  ...
  [ 9.  8.  9.]
  [ 8.  8.  8.]
  [ 7.  7.  7.]]

 [[17. 17. 17.]
  [19. 19. 19.]
  [20. 19. 20.]
  ...
  [36. 36. 36.]
  [33. 32. 33.]
  [33. 32. 33.]]

 ...

 [[16. 16. 16.]
  [42. 42. 42.]
  [80. 80. 80.]
  ...
  [10.  9. 10.]
  [ 4.  4.  4.]
  [ 4.  4.  4.]]

 [[11. 11. 11.]
  [39. 38. 39.]
  [77. 77. 77.]
  ...
  [ 6.  6.  6.]
  [ 5.  5.  5.]
  [ 5.  4.  5.]]

 [[13. 12. 13.]
  [45. 45. 45.]
  [92. 91. 92.]
  ...
  [10. 10. 10.]
  [10.  9. 10.]
  [10.  9. 10.]]]
